package com.vondrastic.gdxgui;

import com.badlogic.gdx.graphics.g2d.TextureRegion;

public interface GameInterface {
	public enum MENU_CMD{NOACTION, VOLUP, VOLDN, VOL_DATA, VOL_MUTE, VOL_ON,
		SCHED_OPEN, SCHED_CLOSE, SCHEDULE_DATA,
		CARDS_MORE, CARDS_LESS, 
		FLASHBOARD_OPEN, FLASHBOARD_CLOSE, FLASHBOARD_DATA,
		FULLSCREEN_ENTER, FULLSCREEN_EXIT,
		DAUBERS_OPEN, DAUBERS_CLOSE, DAUBERS_DATA, DAUBER_ACCEPT, DAUBER_CANCEL,
		PATTERN_OPEN, PATTERN_CLOSE, PATTERN_DATA,
		GAMES_OPEN, GAMES_CLOSE,
		GAMES_NEXT, GAMES_BACK,
		GAMES_SELECTED, GAMES_CANCEL,
		KEYPAD_OPEN, KEYPAD_CLOSE, KEYPAD_DATA,
		NET_NEW_MESSAGE,
		EXIT_YES, EXIT_CANCEL,EXIT_MSGBOX,
		QUIT_YES, QUIT_CANCEL, QUIT_MSGBOX,
		SETTINGS_OPEN, SETTINGS_CLOSE,
		TRIVIA_CORRECT, TRIVIA_WRONG,
		UPDATE_YES, UPDATE_CANCEL
		}
	
	public void GameMessage(MENU_CMD MC);
	public void GameMessage(MENU_CMD MC, int data);
	public void GameMessage(MENU_CMD MC, TextureRegion data);
	public void GameMessage(MENU_CMD MC, String data);
	public void GameMessage(MENU_CMD MC, byte[] data);
	
}
